import { defaultCourses } from "@/components/courses/course-grid"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { ArrowLeft, ArrowRight, Play, Pause } from "lucide-react"
import Link from "next/link"

export async function generateStaticParams() {
  const params = []
  
  for (const course of defaultCourses) {
    for (let lessonIndex = 1; lessonIndex <= course.lessons; lessonIndex++) {
      params.push({
        courseId: course.id,
        lessonId: lessonIndex.toString(),
      })
    }
  }
  
  return params
}

interface LessonContent {
  title: string
  content: string[]
  audioFrequency?: number
  practiceMinutes?: number
  keyPoints: string[]
  exercises: {
    title: string
    description: string
    duration: string
  }[]
}

// Detailed content for Schumann Resonance Fundamentals course
const lessonContents: Record<string, LessonContent[]> = {
  "1": [
    // Lesson 1
    {
      title: "Introduction to Earth's Electromagnetic Field",
      content: [
        "The Earth's electromagnetic field is a powerful force that surrounds our planet and influences all life forms. This natural phenomenon creates a complex network of energy that we can tap into for healing and consciousness expansion.",
        "In this lesson, we'll explore the basic principles of electromagnetic fields, their measurement, and how they interact with biological systems. You'll learn about the ionosphere, the magnetosphere, and how they create the perfect conditions for the Schumann Resonances.",
        "The Earth's magnetic field is generated by the planet's molten core and extends far into space, creating a protective shield known as the magnetosphere. This field is crucial for life on Earth, shielding us from harmful solar radiation and creating the conditions necessary for the Schumann Resonances to occur."
      ],
      keyPoints: [
        "Earth's electromagnetic field basics",
        "Ionosphere and magnetosphere interaction",
        "Impact on biological systems",
        "Introduction to field measurement"
      ],
      exercises: [
        {
          title: "Field Awareness Meditation",
          description: "A guided meditation to help you become aware of Earth's electromagnetic field",
          duration: "10 minutes"
        },
        {
          title: "Frequency Journaling",
          description: "Document your experiences and sensations when focusing on Earth's field",
          duration: "5 minutes"
        }
      ]
    },
    // Lesson 2
    {
      title: "The Discovery of Schumann Resonances",
      content: [
        "Professor Winfried Otto Schumann first predicted the existence of these resonances in 1952. This lesson covers the fascinating history of their discovery and the scientific principles behind them.",
        "We'll explore how these resonances are created, measured, and why they remain relatively constant. You'll learn about the significance of the 7.83 Hz base frequency and its harmonics.",
        "The relationship between these frequencies and human consciousness is a key focus, as we examine the research showing how our brains naturally synchronize with Earth's rhythms."
      ],
      audioFrequency: 7.83,
      practiceMinutes: 15,
      keyPoints: [
        "Historical discovery by W.O. Schumann",
        "Scientific principles of resonance",
        "Measurement techniques",
        "Connection to human consciousness"
      ],
      exercises: [
        {
          title: "7.83 Hz Attunement",
          description: "Experience the base Schumann frequency with guided meditation",
          duration: "15 minutes"
        },
        {
          title: "Resonance Observation",
          description: "Practice identifying different frequency sensations",
          duration: "10 minutes"
        }
      ]
    },
    // Lesson 3
    {
      title: "7.83 Hz: The Earth's Heartbeat",
      content: [
        "The 7.83 Hz frequency, often called the Earth's heartbeat, is the fundamental Schumann Resonance. This frequency has profound implications for human health and consciousness.",
        "Research has shown that when humans are exposed to this frequency, it can help regulate circadian rhythms, reduce stress, and enhance overall wellbeing. This is because our brains have evolved alongside this planetary rhythm.",
        "In this lesson, we'll dive deep into the significance of 7.83 Hz and learn practical techniques to attune ourselves to this fundamental frequency."
      ],
      audioFrequency: 7.83,
      practiceMinutes: 20,
      keyPoints: [
        "Understanding 7.83 Hz in detail",
        "Health benefits and research",
        "Brain entrainment principles",
        "Practical application methods"
      ],
      exercises: [
        {
          title: "Earth Frequency Meditation",
          description: "Deep meditation synchronized with 7.83 Hz",
          duration: "20 minutes"
        },
        {
          title: "Grounding Practice",
          description: "Physical exercises to connect with Earth's frequency",
          duration: "15 minutes"
        }
      ]
    },
    // Lesson 4
    {
      title: "Frequency Entrainment Basics",
      content: [
        "Frequency entrainment is the process by which one oscillating system synchronizes with another. In this context, we'll learn how our brains can naturally attune to the Schumann Resonances.",
        "Understanding brainwave states - Delta, Theta, Alpha, Beta, and Gamma - is crucial for working with frequency entrainment. We'll explore how each state corresponds to different levels of consciousness and healing potential.",
        "You'll learn practical techniques to facilitate entrainment and how to recognize when you're successfully synchronized with these beneficial frequencies."
      ],
      audioFrequency: 7.83,
      practiceMinutes: 25,
      keyPoints: [
        "Principles of entrainment",
        "Brainwave states overview",
        "Synchronization techniques",
        "Recognition of entrainment"
      ],
      exercises: [
        {
          title: "Progressive Entrainment",
          description: "Step-by-step practice of frequency synchronization",
          duration: "25 minutes"
        },
        {
          title: "State Shifting",
          description: "Practice moving between different brainwave states",
          duration: "20 minutes"
        }
      ]
    },
    // Lesson 5
    {
      title: "Binaural Beats and Brain States",
      content: [
        "Binaural beats are a powerful tool for frequency work. When two slightly different frequencies are played in each ear, the brain creates a third frequency equal to the difference between them.",
        "This lesson explores how to use binaural beats effectively with the Schumann Resonances. We'll learn about different frequency combinations and their specific effects on consciousness.",
        "You'll discover how to create your own binaural beat sessions and how to optimize them for different purposes such as meditation, healing, or enhanced focus."
      ],
      audioFrequency: 7.83,
      practiceMinutes: 30,
      keyPoints: [
        "Binaural beats explained",
        "Frequency combinations",
        "Application techniques",
        "Session design principles"
      ],
      exercises: [
        {
          title: "Binaural Beat Experience",
          description: "Guided session with various frequency combinations",
          duration: "30 minutes"
        },
        {
          title: "Personal Session Design",
          description: "Create your own binaural beat practice",
          duration: "15 minutes"
        }
      ]
    },
    // Lesson 6
    {
      title: "Practical Applications in Daily Life",
      content: [
        "This lesson focuses on integrating Schumann Resonance practices into your daily routine. We'll explore practical ways to maintain connection with these frequencies throughout your day.",
        "Learn how to create a frequency-optimized environment at home and work, including the use of technology and natural methods to enhance exposure to beneficial frequencies.",
        "We'll also discuss how to protect yourself from harmful electromagnetic frequencies while maximizing the benefits of natural Earth resonances."
      ],
      keyPoints: [
        "Daily integration techniques",
        "Environmental optimization",
        "EMF protection methods",
        "Lifestyle enhancement"
      ],
      exercises: [
        {
          title: "Daily Rhythm Setting",
          description: "Establish a frequency-aware daily routine",
          duration: "Throughout the day"
        },
        {
          title: "Environment Assessment",
          description: "Evaluate and optimize your space for frequency work",
          duration: "30 minutes"
        }
      ]
    },
    // Lesson 7
    {
      title: "Advanced Frequency Combinations",
      content: [
        "Beyond the base 7.83 Hz, there are several harmonic Schumann Resonances that can be used in combination for enhanced effects. This lesson explores these higher frequencies and their applications.",
        "We'll study the relationships between different Schumann harmonics and how they can be used together for specific purposes such as deep healing, enhanced creativity, or spiritual connection.",
        "Learn about the mathematical relationships between frequencies and how to create powerful combinations for your practice."
      ],
      audioFrequency: 14.3,
      practiceMinutes: 35,
      keyPoints: [
        "Harmonic relationships",
        "Frequency stacking",
        "Application strategies",
        "Advanced combinations"
      ],
      exercises: [
        {
          title: "Harmonic Meditation",
          description: "Experience multiple Schumann harmonics",
          duration: "35 minutes"
        },
        {
          title: "Frequency Mapping",
          description: "Create your own frequency combinations",
          duration: "20 minutes"
        }
      ]
    },
    // Lesson 8
    {
      title: "Healing with Schumann Resonances",
      content: [
        "The healing potential of Schumann Resonances is vast. This lesson explores specific applications for physical, emotional, and energetic healing.",
        "We'll examine case studies and research showing the effects of these frequencies on various health conditions, and learn protocols for different healing applications.",
        "You'll learn how to create targeted healing sessions using specific frequency combinations and how to measure their effectiveness."
      ],
      audioFrequency: 7.83,
      practiceMinutes: 40,
      keyPoints: [
        "Healing protocols",
        "Condition-specific applications",
        "Measurement methods",
        "Progress tracking"
      ],
      exercises: [
        {
          title: "Healing Session",
          description: "Complete healing protocol with multiple frequencies",
          duration: "40 minutes"
        },
        {
          title: "Results Documentation",
          description: "Track and analyze healing effects",
          duration: "10 minutes"
        }
      ]
    },
    // Lesson 9
    {
      title: "Consciousness Expansion",
      content: [
        "Schumann Resonances can be powerful tools for expanding consciousness and accessing higher states of awareness. This lesson explores advanced techniques for spiritual development.",
        "Learn how to use these frequencies to enhance meditation, facilitate astral projection, and deepen your spiritual practice.",
        "We'll also explore the relationship between Schumann Resonances and various states of consciousness described in ancient spiritual traditions."
      ],
      audioFrequency: 20.3,
      practiceMinutes: 45,
      keyPoints: [
        "Consciousness states",
        "Spiritual applications",
        "Advanced meditation",
        "Integration practices"
      ],
      exercises: [
        {
          title: "Consciousness Expansion",
          description: "Guided journey through different states",
          duration: "45 minutes"
        },
        {
          title: "Integration Practice",
          description: "Ground and integrate expanded states",
          duration: "15 minutes"
        }
      ]
    },
    // Lesson 10
    {
      title: "Group Work and Collective Fields",
      content: [
        "Working with Schumann Resonances in groups can create powerful field effects. This lesson explores how to facilitate group sessions and create collective resonance.",
        "Learn about the amplification effects of group practice and how to organize and lead frequency work with others.",
        "We'll also examine research on collective consciousness and how frequency work can contribute to global coherence."
      ],
      audioFrequency: 7.83,
      practiceMinutes: 50,
      keyPoints: [
        "Group facilitation",
        "Field amplification",
        "Collective coherence",
        "Leadership skills"
      ],
      exercises: [
        {
          title: "Group Resonance",
          description: "Practice creating collective field effects",
          duration: "50 minutes"
        },
        {
          title: "Facilitation Practice",
          description: "Learn to guide others in frequency work",
          duration: "30 minutes"
        }
      ]
    },
    // Lesson 11
    {
      title: "Research and Documentation",
      content: [
        "Understanding and documenting your work with Schumann Resonances is crucial for both personal development and contributing to the field.",
        "Learn scientific methods for measuring and documenting frequency effects, including the use of various monitoring tools and documentation techniques.",
        "We'll explore current research in the field and how to design your own experiments and studies."
      ],
      keyPoints: [
        "Research methods",
        "Documentation techniques",
        "Measurement tools",
        "Experimental design"
      ],
      exercises: [
        {
          title: "Research Design",
          description: "Create your own frequency research protocol",
          duration: "40 minutes"
        },
        {
          title: "Data Collection",
          description: "Practice documenting frequency effects",
          duration: "20 minutes"
        }
      ]
    },
    // Lesson 12
    {
      title: "Integration and Moving Forward",
      content: [
        "In this final lesson, we'll integrate everything you've learned and create a plan for continuing your work with Schumann Resonances.",
        "Learn how to design your own advanced practices and potentially contribute to this evolving field.",
        "We'll explore opportunities for further study and how to share this knowledge with others responsibly."
      ],
      audioFrequency: 7.83,
      practiceMinutes: 60,
      keyPoints: [
        "Knowledge integration",
        "Advanced practice design",
        "Future opportunities",
        "Teaching preparation"
      ],
      exercises: [
        {
          title: "Final Integration",
          description: "Comprehensive practice session",
          duration: "60 minutes"
        },
        {
          title: "Future Planning",
          description: "Create your ongoing practice plan",
          duration: "30 minutes"
        }
      ]
    }
  ]
}

export default function LessonPage({ 
  params 
}: { 
  params: { courseId: string; lessonId: string } 
}) {
  const course = defaultCourses.find(c => c.id === params.courseId)
  const lessonIndex = parseInt(params.lessonId) - 1
  const lessonContent = lessonContents[params.courseId]?.[lessonIndex]

  if (!course || !lessonContent) {
    return <div>Lesson not found</div>
  }

  const totalLessons = course.topics.length
  const nextLesson = lessonIndex < totalLessons - 1 ? lessonIndex + 2 : null
  const prevLesson = lessonIndex > 0 ? lessonIndex : null

  return (
    <main className="container mx-auto py-8">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Navigation */}
        <div className="flex items-center justify-between">
          <Link href={`/courses/${params.courseId}`}>
            <Button variant="ghost">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Course
            </Button>
          </Link>
          <div className="flex items-center gap-2">
            {prevLesson !== null && (
              <Link href={`/courses/${params.courseId}/lessons/${prevLesson}`}>
                <Button variant="outline">Previous Lesson</Button>
              </Link>
            )}
            {nextLesson && (
              <Link href={`/courses/${params.courseId}/lessons/${nextLesson}`}>
                <Button>Next Lesson</Button>
              </Link>
            )}
          </div>
        </div>

        {/* Progress */}
        <div className="space-y-2">
          <Progress value={(lessonIndex + 1) * (100 / totalLessons)} />
          <p className="text-sm text-muted-foreground">
            Lesson {lessonIndex + 1} of {totalLessons}
          </p>
        </div>

        {/* Lesson Content */}
        <div className="space-y-8">
          <h1 className="text-4xl font-bold">{lessonContent.title}</h1>
          
          {/* Main Content */}
          <div className="space-y-4 text-lg">
            {lessonContent.content.map((paragraph, index) => (
              <p key={index}>{paragraph}</p>
            ))}
          </div>

          {/* Frequency Practice */}
          {lessonContent.audioFrequency && (
            <Card>
              <CardHeader>
                <CardTitle>Frequency Practice</CardTitle>
                <CardDescription>
                  Experience the {lessonContent.audioFrequency} Hz frequency
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center justify-center">
                    <Button size="lg" className="w-32">
                      <Play className="mr-2 h-4 w-4" />
                      Play
                    </Button>
                  </div>
                  <p className="text-sm text-center text-muted-foreground">
                    Recommended practice time: {lessonContent.practiceMinutes} minutes
                  </p>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Key Points */}
          <Card>
            <CardHeader>
              <CardTitle>Key Points</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {lessonContent.keyPoints.map((point, index) => (
                  <li key={index} className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary" />
                    {point}
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {/* Exercises */}
          <Card>
            <CardHeader>
              <CardTitle>Practical Exercises</CardTitle>
              <CardDescription>
                Complete these exercises to deepen your understanding
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {lessonContent.exercises.map((exercise, index) => (
                  <div key={index} className="space-y-2">
                    <h3 className="font-semibold">{exercise.title}</h3>
                    <p className="text-muted-foreground">{exercise.description}</p>
                    <p className="text-sm">Duration: {exercise.duration}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  )
} 