[build]
  command = "python3 --version && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://schumann-app.netlify.app"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8"
  USE_PYTHON_VERSION = "3.8"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/standalone/**"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "next"
  targetPort = 3000 